/**
 * accordion/theory/circle-of-fifths.ts
 *
 * Unified circle-of-fifths lookup table for all accordion layout types.
 *
 * The table has 12 entries (one per pitch class), ordered by circle position
 * starting from C (pos 0) going sharpward (clockwise): C–G–D–A–E–B–F#–C#–G#–D#–A#–F.
 *
 * Each entry stores both the sharp and flat spellings of the note name and its
 * counterbass (major 3rd above). The `flat` spelling for pos 6 is 'F#' (not 'Gb')
 * per project convention. The `cb` field is always unambiguous in practice
 * (flat-side roots all have natural-note counterbasses; sharp-side roots use sharps).
 *
 * Helper `buildStradellaRows` derives NOTE_ROWS arrays for any Stradella config,
 * eliminating per-config note-name tables and CB_LABEL lookups.
 *
 * Exports: FifthsNote, FIFTHS, Spelling, buildStradellaRows
 */

/** One entry in the circle of fifths. */
export interface FifthsNote {
  /** Circle position: 0 = C, 1 = G, 2 = D, … 6 = F#, … 11 = F (sharpward order). */
  pos: number;
  /** MIDI pitch class 0–11 (C = 0). */
  pc: number;
  /** Sharp / natural spelling: C G D A E B F# C# G# D# A# F */
  sharp: string;
  /** Flat / natural spelling: same as sharp except C#→Db, G#→Ab, D#→Eb, A#→Bb. F#/Gb always 'F#'. */
  flat: string;
  /** Counterbass note name (root + major 3rd = +4 semitones). Always unambiguous. */
  cb: string;
  /**
   * Standard outer-register MIDI for Stradella bass (low register).
   * Inner register = bassMidi + 12.
   * Values keep notes roughly in the A#1–C3 range (MIDI 34–48).
   */
  bassMidi: number;
}

/**
 * Circle of fifths, indexed by position (0 = C, sharpward).
 * Flat-side variable notes (pos 7–10) have natural counterbasses;
 * sharp-side variable notes (pos 2–6) have sharp counterbasses.
 */
export const FIFTHS: readonly FifthsNote[] = [
  { pos: 0,  pc: 0,  sharp: 'C',  flat: 'C',  cb: 'E',  bassMidi: 48 },
  { pos: 1,  pc: 7,  sharp: 'G',  flat: 'G',  cb: 'B',  bassMidi: 43 },
  { pos: 2,  pc: 2,  sharp: 'D',  flat: 'D',  cb: 'F#', bassMidi: 38 },
  { pos: 3,  pc: 9,  sharp: 'A',  flat: 'A',  cb: 'C#', bassMidi: 45 },
  { pos: 4,  pc: 4,  sharp: 'E',  flat: 'E',  cb: 'G#', bassMidi: 40 },
  { pos: 5,  pc: 11, sharp: 'B',  flat: 'B',  cb: 'D#', bassMidi: 35 },
  { pos: 6,  pc: 6,  sharp: 'F#', flat: 'Gb', cb: 'A#', bassMidi: 42 },
  { pos: 7,  pc: 1,  sharp: 'C#', flat: 'Db', cb: 'F',  bassMidi: 37 },
  { pos: 8,  pc: 8,  sharp: 'G#', flat: 'Ab', cb: 'C',  bassMidi: 44 },
  { pos: 9,  pc: 3,  sharp: 'D#', flat: 'Eb', cb: 'G',  bassMidi: 39 },
  { pos: 10, pc: 10, sharp: 'A#', flat: 'Bb', cb: 'D',  bassMidi: 34 },
  { pos: 11, pc: 5,  sharp: 'F',  flat: 'F',  cb: 'A',  bassMidi: 41 },
];

/** Note-name spelling preference. */
export type Spelling = 'sharp' | 'flat';

/** One row of a Stradella bass layout. */
export interface StradellaRow {
  /** Note name using the requested spelling. */
  note: string;
  /** MIDI note number for the bass button. */
  bassMidi: number;
  /** Counterbass note name (major 3rd above root). */
  cb: string;
  /** Circle-of-fifths position (0–11). */
  pos: number;
}

/**
 * Build an ordered array of bass row definitions for any Stradella layout.
 *
 * Rows are generated by walking the circle of fifths in the **flatward** direction
 * (descending 5ths / ascending 4ths), which matches the physical top-to-bottom
 * order of Stradella buttons on an accordion (e.g. A#→D#→G#→…→F for 120-bass).
 *
 * @param startPos  Circle position of the topmost row (default 10 = A#/Bb for standard Stradella).
 * @param count     Number of rows to generate (e.g. 12 for outer, 8 for inner, 20 total).
 * @param spelling  'sharp' | 'flat', or a function `(pos) => Spelling` for mixed registers.
 * @param midiOffset  Added to each `bassMidi` value — use 0 for low/outer register (default),
 *                    12 for high/inner register (one octave up).
 */
export function buildStradellaRows(
  startPos: number,
  count: number,
  spelling: Spelling | ((pos: number) => Spelling),
  midiOffset = 0,
): StradellaRow[] {
  const rows: StradellaRow[] = [];
  for (let i = 0; i < count; i++) {
    const pos = ((startPos - i) % 12 + 12) % 12;
    const entry = FIFTHS[pos];
    const sp = typeof spelling === 'function' ? spelling(pos) : spelling;
    rows.push({
      note:     sp === 'sharp' ? entry.sharp : entry.flat,
      bassMidi: entry.bassMidi + midiOffset,
      cb:       entry.cb,
      pos,
    });
  }
  return rows;
}

/**
 * The three tactile reference rows on a standard Stradella bass panel.
 * C is the primary marker; G#/Ab and E are secondary (each 4 fifths from C,
 * dividing the panel into thirds). Both enharmonic spellings are included
 * since outer and inner registers use different conventions.
 */
export const TACTILE_MARKER_ROOTS = new Set(['C', 'G#', 'Ab', 'E']);
